app/models.py
from flask import Flask,url_for
from flask_sqlalchemy import SQLAlchemy
db=SQLAlchemy()

class Book(db.Model):
    __tablename__="book"
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(20))
    cover_photo=db.Column(db.String(50))
    number_of_pages=db.Column(db.Integer)
    description=db.Column(db.String(100))

    @property
    def image_url(self):
        return url_for ("static",filename=f"images/{self.cover_photo}")

    @property
    def show_url(self):
        return url_for ("book.show",id=self.id)
    @property
    def delete_url(self):
        return url_for ("book.delete",id=self.id)

app/book/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, FileField
from wtforms.validators import DataRequired

class Form(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    description = StringField("Description", validators=[DataRequired()])
    number_of_pages = IntegerField("Number of Pages", validators=[DataRequired()])
    image = FileField("Image", validators=[DataRequired()])
    submit = SubmitField("Create Book")

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from app.config import productionConfig
from app.models import db
from app.book.views import landing_blueprint, book_blueprint  
from flask_bootstrap import Bootstrap5

def create_app():
    app = Flask(__name__)
    
    app.config.from_object(productionConfig)
    
    db.init_app(app)  
    migrate = Migrate(app, db)  
    bootstrap = Bootstrap5(app)  

    app.register_blueprint(landing_blueprint, url_prefix="/")  
    app.register_blueprint(book_blueprint, url_prefix="/books")  

    return app

app/book/__init__.py
from flask import Blueprint
book_blueprint=Blueprint("book",__name__,url_prefix="/book")
landing_blueprint=Blueprint("landing",__name__,url_prefix="/")
from app.book import views

app/book/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.book.forms import Form
from app.models import Book, db
from werkzeug.utils import secure_filename
import os


landing_blueprint = Blueprint('landing', __name__, template_folder='templates')
book_blueprint = Blueprint('book', __name__, template_folder='templates')

@landing_blueprint.route("/", endpoint="index")
def index():
    books = Book.query.all()
    return render_template("index.html", books=books)

@book_blueprint.route("<int:id>/show", endpoint="show")
def show(id):
    book = db.get_or_404(Book, id)
    return render_template("show.html", book=book)

@book_blueprint.route("<int:id>/delete", endpoint="delete")
def delete(id):
    book = db.get_or_404(Book, id)
    db.session.delete(book)
    db.session.commit()
    return redirect(url_for("landing.index"))

@book_blueprint.route("/form/add", endpoint="add", methods=['GET', 'POST'])
def add():
    form = Form()
    if form.validate_on_submit():
        image = form.image.data 
        if image:
            image_name = secure_filename(image.filename)
            image.save(os.path.join('static/images/', image_name))
        else:
            image_name = None

        data = dict(request.form)
        del data['csrf_token']
        del data['submit']
        data["cover_photo"] = image_name

        book = Book(**data)
        db.session.add(book)
        db.session.commit()
        return redirect(url_for("landing.index"))

    return render_template("add.html", form=form)

@book_blueprint.route("<int:id>/form/edit", endpoint="edit", methods=['GET', 'POST'])
def edit(id):
    book = db.get_or_404(Book, id)
    form = Form(obj=book)

    if form.validate_on_submit():

        if 'image' in request.files:
            image = form.image.data
            if image:
                image_name = secure_filename(image.filename)
                image.save(os.path.join('static/images/', image_name))
                book.cover_photo = image_name
        
        book.title = form.title.data
        book.number_of_pages = form.number_of_pages.data
        book.description = form.description.data
        db.session.commit()
        return redirect(url_for("landing.index"))
    
    return render_template("edit.html", form=form)

app/templates/add.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
<title>Add Book</title>
{% endblock %}

{% block main %}
<div class="container mt-4">
    <h1 class="mb-4">Please Enter Book Details</h1>
    <div class="card p-4">
        {{ render_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block title %}{% endblock %}
</head>
<body>
    <main role="main" class="container">
        {% block main %}{% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

app/templates/edit.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}

{% block title %}
<title>Edit Book</title>
{% endblock %}

{% block main %}
<div class="container mt-4">
    <h1 class="mb-4">Update Your Book Details</h1>
    <div class="card p-4">
        <form method="post" enctype="multipart/form-data">
            {{ render_form(form) }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block title %}
<title>Book Library</title>
{% endblock %}

{% block main %}
<div class="container mt-4">
    <h1 class="mb-4">Welcome to My Books Library</h1>
    <a class="btn btn-primary mb-4" href="{{ url_for('book.add') }}">Add Book</a>
    <div class="row">
        {% for book in books %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ book.image_url }}" class="card-img-top" alt="{{ book.title }}" style="width: 200px; height: 300px; object-fit: cover;">
                <div class="card-body">
                    <h5 class="card-title">{{ book.title }}</h5>
                    <p class="card-text">{{ book.description }}</p>
                    <p><strong>Pages:</strong> {{ book.number_of_pages }}</p>
                    <a href="{{ book.show_url }}" class="btn btn-info">Show Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/show.html
{% extends "base.html" %}
{% block title %}
<title>Book Details</title>
{% endblock %}

{% block main %}
<div class="container mt-4">
    <div class="card">
        <img src="{{ book.image_url }}" class="card-img-top" alt="{{ book.title }}" style="width: 200px; height: 300px; object-fit: cover;">
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.description }}</p>
            <p><strong>Pages:</strong> {{ book.number_of_pages }}</p>
            <a href="{{ book.delete_url }}" class="btn btn-danger">Delete</a>
            <a href="{{ url_for('book.edit', id=book.id) }}" class="btn btn-warning">Edit</a>
        </div>
    </div>
</div>
{% endblock %}